### ISSUE TITLE
Add option to disable success message

### ISSUE THREAD

**Issue by mxstbr** [macklinu/danger-plugin-jest#25]
I don't particularly care to see the Danger comment if the Jest tests pass, I can see that in the commit status, I mainly care about seeing the test failures right on GitHub when they fail!

It'd be great if there was an option to disable posting a success message so the comment gets deleted once all tests pass:

<img width="808" alt="screen shot 2017-10-10 at 9 31 17 pm" src="https://user-images.githubusercontent.com/7525670/31406656-7671bd2a-ae02-11e7-92f4-6d1f1f6b780e.png">

/cc @orta

**Comment by macklinu** [comment]
I'd be open to removing this behavior by default in v2.0 while also supplying a `successMessage` option for those who would like the current behavior. Wondering if having a message at all on success is valuable - you make a good point with the GitHub commit status being ✅, so having a message for every success might just become unnecessary noise.

**Comment by mxstbr** [comment]
Sounds great to me!

**Comment by orta** [comment]
I removed that message in #23

**Comment by macklinu** [comment]
I think this was resolved in #23. 🙇
