### ISSUE TITLE
In search of example CircleCI config.yml

### ISSUE THREAD

**Issue by alessbell** [macklinu/danger-plugin-jest#43]
First off, thanks for open sourcing this!

I'm having some trouble using this plugin with CircleCI. To be clear, my issue is with CircleCI itself: I seem to be unable to persist my jest output, `test-results.json`, [from one job to the next](https://discuss.circleci.com/t/persist-to-workspace-doesnt-run-after-a-failed-test-command/25997) when the tests fail.

_Tl;dr:_ the `persist_to_workspace` step doesn't run after my test step fails in the same job, so I have no way of accessing the results in the next job where I run Danger.

If anyone can shed some light on this issue, I'd appreciate it! I fully expect this issue to be closed immediately, but thought it was worth a shot in case anyone can share a working config.yml, or has suggestions. Thanks!

**Comment by macklinu** [comment]
Would you be able to use the `store_test_results` or `store_artifacts` steps to access the `test-results.json` file (looking at [these Circle CI docs](https://circleci.com/docs/2.0/collect-test-data/)). I'm not that familiar with the Circle CI 2.0, so I'm sorry I can't provide more specific help here.

**Comment by alessbell** [comment]
Thanks for the suggestions @macklinu! Looks like `store_test_results` and `store_artifacts` only work with files stored in XML xUnit format from what I can see.

In the end I was able to get this working by running the tests inside a shell script that can optionally record the failure in an env var, then return 0 so the `persist_to_workspace` step can run.

In theory, after that you could have a new step that conditionally throws an error based on the env var, but that turned out not to be necessary because the danger job with `danger-plugin-jest` will fail the build once it can read the test results. Here's a [gist with my jobs config](https://gist.github.com/alessbell/d5538e79bb905a2dcf384c7d8232bed0) if it's useful to anyone. Thanks again!
